// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvvCSA8hWNTMsMxnO3kfZguZw7OiQ7nwk',
    appId: '1:451198024130:android:ffd152c94a90fcbe3abe5b',
    messagingSenderId: '451198024130',
    projectId: 'flutter-hf-af81e',
    storageBucket: 'flutter-hf-af81e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPaGEGwEtXNud_snH-7cBKRQ-Mx2suAjY',
    appId: '1:451198024130:ios:9e76c4834bd686dd3abe5b',
    messagingSenderId: '451198024130',
    projectId: 'flutter-hf-af81e',
    storageBucket: 'flutter-hf-af81e.appspot.com',
    iosBundleId: 'org.zeleim.flutterHf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPaGEGwEtXNud_snH-7cBKRQ-Mx2suAjY',
    appId: '1:451198024130:ios:9e76c4834bd686dd3abe5b',
    messagingSenderId: '451198024130',
    projectId: 'flutter-hf-af81e',
    storageBucket: 'flutter-hf-af81e.appspot.com',
    iosBundleId: 'org.zeleim.flutterHf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC8yDiW0N5Q5LMlaRJAx5gciDu3eMygV5w',
    appId: '1:451198024130:web:fa0c72b0a17b1b1b3abe5b',
    messagingSenderId: '451198024130',
    projectId: 'flutter-hf-af81e',
    authDomain: 'flutter-hf-af81e.firebaseapp.com',
    storageBucket: 'flutter-hf-af81e.appspot.com',
  );

}